### ISSUE TITLE
Sales Screen Not Updating

### ISSUE THREAD

**Issue by dykstranet** [thebitcoincoop/coinos#50]
Sales screen does not update properly with correct currency. Always shows CAD. Also missing some transactions. Recent transactions not displayed on sales screen.

See example in the video : https://youtu.be/Qav3DMevma8

**Comment by asoltys** [comment]
Thanks for reporting this Gary.  I have it displaying the currently selected currency now.  Keep in mind though that if you change your currency after receiving some transactions, this page won't update the converted values and exchange rates of those past transactions.  So it might be misleading to see ZAR on this page now for transactions that were originally received in IDR, for example. 

As for the missing transactions, I suspect that was due to a bug with some email notifications code I was working on which has hopefully been fixed in a separate commit.  Please let me know though if you still notice transactions not being logged properly.
